version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: jira_postgres
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
      POSTGRES_DB: jira
    ports:
      - "5434:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./seeds:/docker-entrypoint-initdb.d/seeds
      - postgres_data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    container_name: jira_api
    restart: always
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://jira:jira@postgres:5432/jira
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    ports:
      - "3000:3000"

volumes:
  postgres_data:



    
